---
- name: ensure rabbitmq is runned
  service: name=rabbitmq-server state=started

- name: add rabbitmq vhost
  rabbitmq_vhost: >
    name={{ item.name }}
    node={{ item.node | default('rabbit') }}
    tracing={{ item.tracing | default('no') }}
    state=present
  with_items: rabbitmq_vhost_definitions

- name: add rabbitmq user and set privileges
  include: add_rabbitmq_user.yml
  when: rabbitmq_users_definitions is not mapping

- name: add rabbitmq user and set privileges
  include: add_rabbitmq_user_mapping.yml
  when: rabbitmq_users_definitions is mapping

- name: remove guest user (hostname)
  rabbitmq_user:
    user=guest
    vhost=/
    node="rabbit@{{ ansible_hostname }}"
    state=absent
  register: rm_guest_hostname
  ignore_errors: true

- name: remove guest user (default)
  rabbitmq_user:
    user=guest
    vhost=/
    state=absent
  when: rm_guest_hostname|failed
